apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
  finalizers:
  - minecraft-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/thetaru/k8s-home.git'
    path: manifests/base/apps/minecraft
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: minecraft
  syncPolicy:
    automated: {}
