apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-server
  namespace: minecraft
spec:
  replicas: 4
  serviceName: minecraft-server
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: server
        image: itzg/minecraft-server
        command: ["/bin/sh", "-c"]
        args:
        - |
          while [ ! -d /configs ]; do echo "Waiting for mount..."; sleep 3; done
          cp -fpL /configs/eula.txt /data && cp -fpL /configs/server.properties /data && cp -fpL /configs/multipaper.yml /data && cp -fpL /configs/bukkit.yml /data && cp -fpL /configs/spigot.yml /data
          apt-get update && apt-get install curl -y
          curl -o /data/multipaper-server.jar https://multipaper.io/api/v2/projects/multipaper/versions/1.19.2/builds/28/downloads/multipaper-1.19.2-28.jar
          java -Xmx6G -Xms4G -DbungeecordName="${HOSTNAME}.minecraft-server.minecraft.svc.cluster.local" -jar /data/multipaper-server.jar
        resources:
          limits:
            memory: "6Gi"
            cpu: "2000m"
        volumeMounts:
        - name: minecraft-server-pvc
          mountPath: "/data"
        - name: minecraft-server-cm
          mountPath: "/configs"
      volumes:
      - name: minecraft-server-cm
        configMap:
          name: minecraft-server-cm
          items:
          - key: "eula.txt"
            path: "eula.txt"
          - key: "server.properties"
            path: "server.properties"
          - key: "multipaper.yml"
            path: "multipaper.yml"
          - key: "bukkit.yml"
            path: "bukkit.yml"
          - key: "spigot.yml"
            path: "spigot.yml"
  volumeClaimTemplates:
  - metadata:
      name: minecraft-server-pvc
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 30Gi
      storageClassName: rook-cephfs
