apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-server-cm
  namespace: minecraft
data:
  eula.txt: |
    eula=true
  server.properties: |
    enable-jmx-monitoring=false
    rcon.port=25575
    level-seed=
    gamemode=survival
    enable-command-block=false
    enable-query=false
    generator-settings={}
    enforce-secure-profile=true
    level-name=world
    motd=A Minecraft Server
    query.port=25565
    pvp=true
    generate-structures=true
    max-chained-neighbor-updates=1000000
    difficulty=easy
    network-compression-threshold=-1
    max-tick-time=60000
    require-resource-pack=false
    use-native-transport=true
    max-players=100
    online-mode=true
    enable-status=true
    allow-flight=false
    broadcast-rcon-to-ops=true
    view-distance=4
    server-ip=
    resource-pack-prompt=
    allow-nether=true
    server-port=25565
    enable-rcon=false
    sync-chunk-writes=true
    op-permission-level=4
    prevent-proxy-connections=false
    hide-online-players=false
    resource-pack=
    entity-broadcast-range-percentage=100
    simulation-distance=10
    rcon.password=
    player-idle-timeout=0
    debug=false
    force-gamemode=false
    rate-limit=0
    hardcore=false
    white-list=false
    broadcast-console-to-ops=true
    spawn-npcs=true
    previews-chat=false
    spawn-animals=true
    function-permission-level=2
    level-type=minecraft\:normal
    text-filtering-config=
    spawn-monsters=true
    enforce-whitelist=false
    spawn-protection=16
    resource-pack-sha1=
    max-world-size=29999984
  multipaper.yml: |
    master-connection:
      advertise-to-built-in-proxy: true
      master-address: minecraft-master.minecraft.svc.cluster.local:35353
      my-name:
    optimizations:
      dont-save-just-for-lighting-updates: true
      reduce-player-position-updates-in-unloaded-chunks: false
      ticks-per-inactive-entity-tracking: 1
      use-event-based-io: true
    peer-connection:
      compression-threshold: 0
      consolidation-delay: 0
    sync-settings:
      files:
        files-to-not-sync:
        - plugins/bStats
        files-to-only-upload-on-server-stop:
        - plugins/MyPluginDirectory/my_big_database.db
        files-to-sync-in-real-time:
        - plugins/MyPluginDirectory/userdata
        files-to-sync-on-startup:
        - myconfigfile.yml
        - plugins/MyPlugin.jar
        log-file-syncs: true
      sync-entity-ids: true
      sync-json-files: true
      sync-permissions: false
      sync-scoreboards: true
      use-local-player-count-for-server-is-full-kick: false
  bukkit.yml: |
    settings:
      allow-end: true
      warn-on-overload: true
      permissions-file: permissions.yml
      update-folder: update
      plugin-profiling: false
      connection-throttle: 4000
      query-plugins: true
      deprecated-verbose: default
      shutdown-message: Server closed
      minimum-api: none
      use-map-color-cache: true
    spawn-limits:
      monsters: 50
      animals: 8
      water-animals: 7
      water-ambient: 10
      water-underground-creature: 5
      axolotls: 5
      ambient: 1
    chunk-gc:
      period-in-ticks: 400
    ticks-per:
      animal-spawns: 400
      monster-spawns: 5
      water-spawns: 11
      water-ambient-spawns: 21
      water-underground-creature-spawns: 1
      axolotl-spawns: 1
      ambient-spawns: 31
      autosave: 6000
    aliases: now-in-commands.yml
  spigot.yml: |
    settings:
      debug: false
      save-user-cache-on-stop-only: false
      sample-count: 12
      netty-threads: 4
      attribute:
        maxHealth:
          max: 2048.0
        movementSpeed:
          max: 2048.0
        attackDamage:
          max: 2048.0
      log-villager-deaths: true
      log-named-deaths: true
      bungeecord: false
      player-shuffle: 0
      user-cache-size: 1000
      moved-wrongly-threshold: 0.0625
      moved-too-quickly-multiplier: 10.0
      timeout-time: 60
      restart-on-crash: true
      restart-script: ./start.sh
    messages:
      whitelist: You are not whitelisted on this server!
      unknown-command: Unknown command. Type "/help" for help.
      server-full: The server is full!
      outdated-client: Outdated client! Please use {0}
      outdated-server: Outdated server! I'm still on {0}
      restart: Server is restarting
    advancements:
      disable-saving: false
      disabled:
      - minecraft:story/disabled
    commands:
      log: true
      tab-complete: 0
      send-namespaced: true
      spam-exclusions:
      - /skill
      silent-commandblock-console: false
      replace-commands:
      - setblock
      - summon
      - testforblock
      - tellraw
    players:
      disable-saving: false
    world-settings:
      default:
        below-zero-generation-in-existing-chunks: true
        wither-spawn-sound-radius: 0
        view-distance: default
        simulation-distance: default
        thunder-chance: 100000
        merge-radius:
          item: 2.5
          exp: 3.0
        item-despawn-rate: 6000
        enable-zombie-pigmen-portal-spawns: true
        hanging-tick-frequency: 100
        arrow-despawn-rate: 1200
        trident-despawn-rate: 1200
        zombie-aggressive-towards-villager: true
        nerf-spawner-mobs: false
        mob-spawn-range: 8
        end-portal-sound-radius: 0
        entity-activation-range:
          animals: 16
          monsters: 24
          raiders: 48
          misc: 8
          water: 16
          villagers: 32
          flying-monsters: 32
          wake-up-inactive:
            animals-max-per-tick: 4
            animals-every: 1200
            animals-for: 100
            monsters-max-per-tick: 8
            monsters-every: 400
            monsters-for: 100
            villagers-max-per-tick: 4
            villagers-every: 600
            villagers-for: 100
            flying-monsters-max-per-tick: 8
            flying-monsters-every: 200
            flying-monsters-for: 100
          villagers-work-immunity-after: 100
          villagers-work-immunity-for: 20
          villagers-active-for-panic: true
          tick-inactive-villagers: true
          ignore-spectators: false
        entity-tracking-range:
          players: 48
          animals: 48
          monsters: 48
          misc: 32
          other: 64
        ticks-per:
          hopper-transfer: 8
          hopper-check: 1
        hopper-amount: 1
        hopper-can-load-chunks: false
        dragon-death-sound-radius: 0
        seed-village: 10387312
        seed-desert: 14357617
        seed-igloo: 14357618
        seed-jungle: 14357619
        seed-swamp: 14357620
        seed-monument: 10387313
        seed-shipwreck: 165745295
        seed-ocean: 14357621
        seed-outpost: 165745296
        seed-endcity: 10387313
        seed-slime: 987234911
        seed-nether: 30084232
        seed-mansion: 10387319
        seed-fossil: 14357921
        seed-portal: 34222645
        seed-stronghold: default
        hunger:
          jump-walk-exhaustion: 0.05
          jump-sprint-exhaustion: 0.2
          combat-exhaustion: 0.1
          regen-exhaustion: 6.0
          swim-multiplier: 0.01
          sprint-multiplier: 0.1
          other-multiplier: 0.0
        max-tnt-per-tick: 100
        max-tick-time:
          tile: 50
          entity: 50
        growth:
          cactus-modifier: 100
          cane-modifier: 100
          melon-modifier: 100
          mushroom-modifier: 100
          pumpkin-modifier: 100
          sapling-modifier: 100
          beetroot-modifier: 100
          carrot-modifier: 100
          potato-modifier: 100
          wheat-modifier: 100
          netherwart-modifier: 100
          vine-modifier: 100
          cocoa-modifier: 100
          bamboo-modifier: 100
          sweetberry-modifier: 100
          kelp-modifier: 100
          twistingvines-modifier: 100
          weepingvines-modifier: 100
          cavevines-modifier: 100
          glowberry-modifier: 100
        verbose: false
    config-version: 12
    stats:
      disable-saving: false
      forced-stats: {}