apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-master
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: master
        image: itzg/minecraft-server
        command: ["/bin/sh", "-c"]
        args:
        - |
          apt-get update && apt-get install curl -y
          curl -o /data/multipaper-master.jar https://multipaper.io/api/v2/projects/multipaper/versions/1.19.2/builds/27/downloads/multipaper-1.19.2-27.jar
          java -Xmx4G -Xms2G -jar /data/multipaper-master.jar 35353
        resources:
          limits:
            memory: "4Gi"
            cpu: "2000m"
        volumeMounts:
        - name: minecraft-master-pvc
          mountPath: "/data"
      volumes:
      - name: minecraft-master-pvc
        persistentVolumeClaim:
          claimName: minecraft-master-pvc
