apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: minecraft-master-pvc 
  namespace: minecraft 
  labels: 
    app: minecraft 
spec: 
  accessModes: 
  - ReadWriteMany 
  resources: 
    requests: 
      storage: 30Gi 
  storageClassName: rook-cephfs
