apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-server-cm
  namespace: minecraft
data:
  eula.txt: |
    eula=true
  server.properties: |
    enable-jmx-monitoring=false
    rcon.port=25575
    level-seed=
    gamemode=survival
    enable-command-block=false
    enable-query=false
    generator-settings={}
    enforce-secure-profile=true
    level-name=world
    motd=A Minecraft Server
    query.port=25565
    pvp=true
    generate-structures=true
    max-chained-neighbor-updates=1000000
    difficulty=easy
    network-compression-threshold=256
    max-tick-time=60000
    require-resource-pack=false
    use-native-transport=true
    max-players=20
    online-mode=true
    enable-status=true
    allow-flight=false
    broadcast-rcon-to-ops=true
    view-distance=10
    server-ip=
    resource-pack-prompt=
    allow-nether=true
    server-port=25565
    enable-rcon=false
    sync-chunk-writes=true
    op-permission-level=4
    prevent-proxy-connections=false
    hide-online-players=false
    resource-pack=
    entity-broadcast-range-percentage=100
    simulation-distance=10
    rcon.password=
    player-idle-timeout=0
    debug=false
    force-gamemode=false
    rate-limit=0
    hardcore=false
    white-list=false
    broadcast-console-to-ops=true
    spawn-npcs=true
    previews-chat=false
    spawn-animals=true
    function-permission-level=2
    level-type=minecraft\:normal
    text-filtering-config=
    spawn-monsters=true
    enforce-whitelist=false
    spawn-protection=16
    resource-pack-sha1=
    max-world-size=29999984
  multipaper.yml: |
    master-connection:
      advertise-to-built-in-proxy: true
      master-address: minecraft-master.minecraft.svc.cluster.local:35353
      my-name:
    optimizations:
      dont-save-just-for-lighting-updates: false
      reduce-player-position-updates-in-unloaded-chunks: false
      ticks-per-inactive-entity-tracking: 1
      use-event-based-io: true
    peer-connection:
      compression-threshold: 0
      consolidation-delay: 0
    sync-settings:
      files:
        files-to-not-sync:
        - plugins/bStats
        files-to-only-upload-on-server-stop:
        - plugins/MyPluginDirectory/my_big_database.db
        files-to-sync-in-real-time:
        - plugins/MyPluginDirectory/userdata
        files-to-sync-on-startup:
        - myconfigfile.yml
        - plugins/MyPlugin.jar
        log-file-syncs: true
      sync-entity-ids: true
      sync-json-files: true
      sync-permissions: false
      sync-scoreboards: true
      use-local-player-count-for-server-is-full-kick: false
